#!/bin/sh

set -e

y_or_exit() {
  /bin/echo -n "$1"
  read yn
  if [ $yn != "y" ]; then
    exit 1
  fi
}

ls node_modules 2> /dev/null 1>&2 && rm -r node_modules
git pull --rebase
npm install
npm test

# bump version
BUMP=`npm run -s release:bump`
y_or_exit "${1:-$BUMP} release? "

cp package.json _package.json
npm --no-git-tag-version version ${1:-$BUMP} &>/dev/null
version=`npm run -s version`
mv -f _package.json package.json

y_or_exit "release $version? "

# build & commit changelog
npm run -s release:build-changelog
git add CHANGELOG.md
git commit -m "docs(CHANGELOG): $version"

# git tag
npm version $version -m "chore(release): %s"
git tag $version

# release 
git push --follow-tags
npm run -s release:github
npm publish
